import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { get } from "./_lib/fetch";
import BoardNav from "./_components/BoardNav";
import UserInfo from "./_components/UserInfo";
import Providers from './providers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Board = {
  id: number;
  name: string;
  orderNo: number;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const boards = await get<Board[]>('http://localhost:8080/api/boards/list');
  
  return (
    <html lang="en">
      <header>
        <UserInfo></UserInfo>
        <BoardNav boards = {boards}></BoardNav>
      </header>
      <body
        className={`antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
