import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { get } from "./_lib/fetch";
import BoardNav from "./_components/BoardNav";
import UserInfo from "./_components/UserInfo";
import Providers from './providers';
import { Board } from "./_types/post";
import { getBoards } from "./_lib/api";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const boards : Board[] = await getBoards();
  
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <UserInfo></UserInfo>
        <BoardNav boards = {boards}></BoardNav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
